language: php
php:
  - '7'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
  - nvm install 8
before_script:
  - npm install
  - composer install
script:
  - npm run build
  - ls -la style.css
  - composer test
deploy:
  provider: script
  script: bash ./bin/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    php: 7
env:
  global:
  - GIT_COMMITTER_NAME=suginoki45
  - GIT_COMMITTER_EMAIL=yuki.sugitani@glatchdesign.com
  - GIT_AUTHOR_NAME=suginoki45
  - GIT_AUTHOR_EMAIL=yuki.sugitani@glatchdesign.com
  - secure: oxK1ST7TDuK0x3BxZJVsuoYComdsFWaEd0SBXAX5foJhHQHCC/ntc2c4TXpNuEI8rPrhy1byhGqwVl0V59/S2PVySfrWYVcERySq5vh/siQinr3WuLuK9k4ML2X//J/03QZ16LIAm4aIsFGdNY1NL3GIDzgKrhd7rM9M2TsgA7a34FrkG0BljEKzwuAMIQrtVb7JbOU2PNXodpHOVSQlBfT5ux6qfduKisOz65k9GxTWzRykwQrrI3+vcu1u97ZFOscotGMHPQZsZJbHw7LXVmdgGd2JX/BSbl97Si0+bkE9D/kjXxKtskhd/HDO481Bicn2WTVHicIcJzOvH2xxCYG04/WtEuavRBi6BEDQdUhbc9sbkdwjJHz+4kV+pc+ZM+HGk3R7KMvOtPX6tYxvd7djIYICdefbO85sT06FSVE5Zb3EKY8Vd+WFBztHztpMdFmqQZ5GrN9Pa6muFWy3V9rpR4aYd4YZw/xrmBhmuphqmbduU7jraOw0NGhmPmkt9yHMYoZrXxDxwoCJUEO7u40asfYWvyxQ5YZR/wAcwqWPqO+U9NGIUH5fkPmnG8b9IXsds63ZQpR9RyI4K1jLDVDKjNw+95+WIoMfxF4VYvEPp/TpqcV44nHUj/NxiefqLl2pQeO2xGeDHqngieLkg2BoFp7RQW0ktqCI+1ygzug=
